CREATE TABLE USER(
ID INT PRIMARY KEY AUTO INCREMENT,
NAME VARCHAR(255) NOT NULL,
PASSWORD VARCHAR(255));

CREATE TABLE PRICE_LIST(
id INT AUTO INCREMENT PRIMARY KEY,
title VARCHAR(36) NOT NULL,
price double NOT NULL);

CREATE TABLE ORDER(
id INT AUTO INCREMENT PRIMARY KEY,
user_id INT,
total_price DOUBLE NOT NULL,
CONSTRAINT user_id FOREIGN KEY (user_id) REFERENCES USER (ID));

CREATE TABLE ORDER_PRICE_LIST(
id INT AUTO INCREMENT PRIMARY KEY,
order_id INT,
good_id INT,
CONSTRAINT order_id FOREIGN KEY (order_id) REFERENCES ORDER (ID),
 CONSTRAINT good_id FOREIGN KEY (good_id) REFERENCES PRICE_LIST (ID));
