INSERT INTO GOODS (TITLE, PRICE)
VALUES ('WHISKEY', 35.0);
INSERT INTO GOODS (TITLE, PRICE)
VALUES ('COLA', 5.0);
INSERT INTO GOODS (TITLE, PRICE)
VALUES ('SODA', 6.0);
INSERT INTO GOODS (TITLE, PRICE)
VALUES ('WATER', 1.0);
INSERT INTO GOODS (TITLE, PRICE)
VALUES ('GIN', 25.0);
INSERT INTO GOODS (TITLE, PRICE)
VALUES ('BEER', 10.0);


INSERT INTO USERS (ID,NAME,PASSWORD)
VALUES (1,'admin','admin');
INSERT INTO ORDERS (ID,user_id,total_price)
VALUES (1,1,0.0);
-- INSERT INTO USERS (NAME,PASSWORD)
-- VALUES ('shade','1234');
