INSERT INTO PRICE_LIST (TITLE, PRICE)
VALUES ('WHISKEY', 35.0);
INSERT INTO PRICE_LIST (TITLE, PRICE)
VALUES ('COLA', 5.0);
INSERT INTO PRICE_LIST (TITLE, PRICE)
VALUES ('SODA', 6.0);
INSERT INTO PRICE_LIST (TITLE, PRICE)
VALUES ('WATER', 1.0);
INSERT INTO PRICE_LIST (TITLE, PRICE)
VALUES ('GIN', 25.0);
INSERT INTO PRICE_LIST (TITLE, PRICE)
VALUES ('BEER', 10.0);


INSERT INTO USERS (NAME,PASSWORD)
VALUES ('admin','admin');
INSERT INTO USERS (NAME,PASSWORD)
VALUES ('shade','1234');
